### ISSUE TITLE
Customize the logout screen

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/cas-overlay#5]
Previously, logging out of a CAS service would show a logout screen with a link to log back in. The login link would have knowledge of the originating service. In other words, users would be able to log back in to the service they just logged out of. 

Currently, the logout screen does not allow you to log back in to the original service:
https://login.bloomington.in.gov/cas/logout

**Comment by inghamn** [comment]
We should customize the logout screen.  The one that's displayed, currently, is the default.
