### ISSUE TITLE
New COB theme

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/cas-overlay#9]
We need to redo the theming in the new version CAS.

**Comment by inghamn** [comment]
#8

**Comment by adabutch** [comment]
I believe this wraps up an initial iteration for the new login skin.

Things to consider for future iterations:
- Logout
- Errors
- Application Reference

**Comment by inghamn** [comment]
The CSS needs to be modified to work with the new HTML in 6.1.3

There will probably be markup changes for every version in the future.

**Comment by inghamn** [comment]
We should have some help information on the login page about what to do with password problems

**Comment by adabutch** [comment]
Andrew sent over a 🔥new logo, vote is to swap it.

**Comment by adabutch** [comment]
This is how my two commits above change things, _this is now how it should look._

@inghamn - can you deploy the update? 😄 PLS & TY!

<img width="503" alt="Screen Shot 2020-01-27 at 3 24 35 PM" src="https://user-images.githubusercontent.com/2372040/73211541-75d3ee80-411a-11ea-851a-bfa8a1eb04b7.png">

**Comment by inghamn** [comment]
We need to figure out a way to prevent browsers from continuing to use the old, cached version of cas.css
